export {default as Navbar } from './Navbar'
export {default as Hero } from './Hero'
export {default as About} from './About'
export {default as HowitWorks} from './HowitWorks'
export {default as Free} from './free'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'
export {default as NavD} from './NavD'
export {default as Sidebar} from './Sidebar'
export {default as DFeed} from './DFeed'
export {default as BottomNav} from './BottomNav'
export {default as Ecards} from './Ecards'
